name: Tagged Go build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/go.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          fail_on_unmatched_files: true
          generate_release_notes: true
